language: python
sudo: false

python:
  - 3.5

env:
  - TOXENV=py27-django18
  - TOXENV=py33-django18
  - TOXENV=py34-django18
  - TOXENV=pypy-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=pypy-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django110
  - TOXENV=py35-django110
  - TOXENV=pypy-django110

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coverage
  - coverage report

services:
  - redis-server
